# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout libuv (for Windows)
      uses: actions/checkout@v3
      with:
        repository: libuv/libuv
        path: libuv-build
        ref: v1.43.0
    - name: Install/build libuv
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install --yes libuv1-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install libuv
        elif [ "$RUNNER_OS" == "Windows" ]; then
          bash build-windows.sh
        else
          echo "Unknown OS"
          exit 1
        fi
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          PATH=build/Debug:$PATH sbt "$SBT_NATIVE_COMPILE $SBT_NATIVE_LINK show nativeCompileOptions ; show nativeLinkingOptions ; test"
        else
          sbt "$SBT_NATIVE_COMPILE $SBT_NATIVE_LINK show nativeCompileOptions ; show nativeLinkingOptions ; test"
        fi
      shell: bash
  
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@v2
